fos_user:
    db_driver: orm
    firewall_name: main
    user_class: EasiestWay\MainBundle\Entity\User

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:      Admin
    options:
        confirm_exit:   false

services:
    gedmo.listener.timestampable:
        class: Gedmo\Timestampable\TimestampableListener
        tags:
            - { name: doctrine.event_subscriber, connection: default }
#        calls:
#            - [ setAnnotationReader, [ '@annotation_reader' ] ]