fos_user:
    db_driver: orm
    firewall_name: main
    user_class: EasiestWay\MainBundle\Entity\User

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]

sonata_admin:
    title:      Admin