<?php

namespace Nippon\PartsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DepotProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepotRepository extends EntityRepository
{

}
